### ISSUE TITLE
2 things: Module not showing up and support for more options

### ISSUE THREAD

**Issue by nixmeer** [Klizzy/MMM-Vrr#1]
Hello :) thank you so much for this module, it looks so much nicer than all other pub transport modules.

1. It worked perfectly fine until yesterday, today it just does not show up. I tried to use standard confit but does not change anything. Any idea what to do?

2. Could you add a separate column for the delay so the time still be perfectly aligned? I think it does not need an extra column title. That would be great!

Thanks in advance

Jan from Essen

**Comment by nixmeer** [comment]
Today it showed up just as expected. No clue what was wrong there. I just booted the pi up this morning.

**Comment by Klizzy** [comment]
Good that its working again!
I will add the extra column for the delay in the next update. 
If your issue shows up again don't hesitate to open a issue again ☺️

**Comment by nixmeer** [comment]
Thank you so much! There is another thing I noticed: connections disappear at their scheduled time, even if they have a delay. It‘d be great if they stayed on the table until the train is departed 

Thanks in advance!

**Comment by Klizzy** [comment]
Hello @nixmeer ,

i updated the module, so the two things shouldn't bother you now ☺️
Just do a `git pull origin master` in the MMM-Vrr module folder, or just download this Modul as a zip and replace the old one.

thanks for the bug report and suggestion! 👍
