### ISSUE TITLE
Funktioniert nicht bei mir - Fehlerhafter Eintrag config.js / Komma vergessen

### ISSUE THREAD

**Issue by Fischje** [Klizzy/MMM-Vrr#10]
Ich bekomme einige Warnungen und Fehlerhinweise beim installieren über npm install. Danach kommt startet der magicmirror nicht mehr richtig. Ist der Code vielleicht nicht mehr aktuell?

**Comment by Klizzy** [comment]
Poste bitte einen Auszug aus den Fehlermeldungen, welche du ausgegeben bekommst.
Weitere folgende Infos würden auch helfen:
- MagicMirror Version
- Node / npm Version (kannst du im Terminal mit `node -v und npm -v` herausfinden)

**Comment by Fischje** [comment]
```
node@magicmirroros:/opt/magic_mirror$ node -v
v14.16.0
node@magicmirroros:/opt/magic_mirror$ npm -v
7.6.1
```
Ich erhalte halt diesen Screen auf dem steht das die Config nicht da wäre oder halt falsch. Ich habe aber in die config.js erstmal nur dein beispiel eingetrtagen. wenn ich den teil aus der config ausklammere läuft der magicmirror.

habe das magicmirror os (docker paket) zur installation genutzt. muss ich den besser selbst installieren auf raspbian?

**Comment by Fischje** [comment]
Habe gerade nochmal auf aktuellen raspbian installiert mit node.js 15 und da funktioniert es leider auch nicht. ich bekomme den fhelr das die config nicht stimmt oder nicht da wäre.

**Comment by Klizzy** [comment]
Ob es mit Docker oder nativ Installiert ist sollte keinen Unterschied machen. 
Kannst du mir bitte noch die Konkrete Fehlermeldung und den Inhalt deiner Config.js hier mitteilen?

Am besten einfach den Kompletten Text der Fehlermeldung einfach aus dem Terminal Kopieren und hier einfügen. Und einmal noch den Inhalt der config.js Das würde deutlich weiterhelfen. 

Das Problem kriegen wir schon gelöst ☺️

**Comment by Klizzy** [comment]
Hey @Fischje ,

ich habe meine Lokale Version mal geupdated und ebenfalls deine `node` und `npm` Versionen installiert. Bei mir Startet der MM sowohl in der `node serveronly` als auch der `npm start` electron Variante ohne Fehler.

Ich vermute das es einen Tipp- oder Copy-Paste Fehler in der `config/config.js` bei dir gibt. In der `config/config.js` ist es wichtig, dass alle `,` oder Klammern korrekt gesetzt sind, da sonst nicht die vollständige Konfiguration ausgelesen werden kann.

Versuch mal ein `,` vor der ersten geschweiften Klammer `{` der MMM-Vrr Modul Konfiguration hinzuzufügen.

Hier habe ich dir das mal Visualisiert:
![MagicMirror_–_config_js](https://user-images.githubusercontent.com/15422170/110250817-c05ea600-7f7d-11eb-907c-dfdc6f311437.png)


Hier habe ich mal den Standardmäßigen Inhalt der `config/config.js.sample` genommen und die Konfiguration für das MMM-Vrr Modul hinzugefügt. Zum Testen könntest du also auch einfach den Kompletten Inhalt Kopieren und den ganzen Inhalt deiner `config/config.js` damit ersetzten. Wenn es damit Funktioniert, dann war es wahrscheinlich ein Tippfehler.

#### config.js
```js
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", 	// Address to listen on, can be:
	// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	// - another specific IPv4/6 to listen on a specific interface
	// - "0.0.0.0", "::" to listen on any interface
	// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					  // you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], 	// Set [] to allow all IP addresses
															  // or add a specific IPv4 of 192.168.1.5 :
															  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															  // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
			module: 'MMM-Vrr',
			position: "top_right",
			config: {
				city: 'Düsseldorf',
				station: 'Hauptbahnhof',
				numberOfResults: 10,
				displayTimeOption: 'countdown',
				displayType: 'detail'
			}
		}
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by Fischje** [comment]
Hallo Klizzy,
wow ! Erstmal vielen Dank für deinen Support. Ich schau mir heute abend nochmal wirklich gaaanz genau den auskommentierten Part an. FAlls es dann immer noch nciht geht poste ich nochmal meine config.js.
Danke schon mal.

**Comment by Fischje** [comment]
Hab es dank dir gefunden. Es war das Komme am Ende des gesamten Moduleintrages, weil ich den Teil irgendwo mitten in die Konfig gepackt habe. Da hab ich wirklich nicht richtig geguckt!
Prima - funktioniert auch bei mir in Mönchengladbach hervorragend!

**Comment by Klizzy** [comment]
Es freut mich, dass es jetzt auch bei dir klappt! Ich werde diese Issue hier damit als gelöst markieren, aber falls noch Anmerkungen, Fragen, Unklarheiten oder ähnliches bestehen - gerne Anschreiben oder eine neue GitHub Issue aufmachen ☺️
