### ISSUE TITLE
LCD Option not updating

### ISSUE THREAD

**Issue by MasterLH** [Klizzy/MMM-Vrr#14]
Hey, ich schreibe mal auf deutsch, hoffe, das ist okay.
Zunächst einmal vielen Dank für das coole Addon, ich bin begeistert von den Funktionen und kann das echt super auf meinem Smart Mirror gebrauchen.

Das Addon funktioniert an und für sich bei mir auch super, jedoch updatet es sich nicht, wenn ich die Display-Anzeige auf LCD-Modus umstelle...
Im "Details" Modus klappt alles einwandfrei und sonst habe ich nichts am Addon oder in der Config bearbeitet...

Habe bereits eine neuinstallation und mehrere Neustarts versucht, auch eine Anpassung des Update Intervalls hilft nicht...

Beim Start vom Magic Mirror zieht sich im LCD-Modus das Addon seine Daten, dann passiert aber leider nichts mehr, die Minuten werden nicht weniger und bereits abgefahrene Linien stehen weiterhin mit der Minutenzahl an, es wirkt wie eingefroren...

Nur wenn ich Magic Mirror neu starte zieht sich das Addon einmal kur die neuen Daten, dann friert es wieder ein.
Im Details Modus hingegen absolut keine Probleme, aber mir gefällt das LCD Aussehen so viel besser :)

Würde mich über einen Fix freuen, viele Grüße

**Comment by MasterLH** [comment]
Dankeschön fürs fixen. Leider kann ich nicht auf die neue Version updaten, da nach dem Update immer der folgende Fehler kommt:

[06.02.2023 14:25.02.168] [ERROR] Error: Cannot find module 'request'
Require stack:
- /opt/magic_mirror/modules/MMM-Vrr/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/js/electron.js
- /opt/magic_mirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Vrr/node_helper.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    
Auch ein Uninstall und Reinstall und das Einfügen der Beispiel-Konfiguration hat nicht geholfen

**Comment by Klizzy** [comment]
@MasterLH 

hmmm, bei dir scheint eine Abhängigkeit zu Fehlen, die eigentlich von der MagicMirror Software mitgeliefert wird.

Ich habe nochmal eine Anpassung vorgenommen und ausgespielt. Folge bitte erneut der [Installationsanweisung](https://github.com/Klizzy/MMM-Vrr#installation), dann sollte sich der Fehler erledigt haben.

**Comment by Klizzy** [comment]
@MasterLH 
Issue wird geschlossen. Falls noch Probleme auftreten, gerne wieder öffnen

**Comment by MasterLH** [comment]
Hey, jetzt funktioniert es tatsächlich!
Leider funktioniert im LCD-Modus die "Line" Auswahl nicht, bzw. es werden trotzdem alle Linien angezeigt. Ändert man dann nur den Display-Type und lässt sonst alle Parameter gleich, funktioniert der "Filter" line wieder...

Vielen lieben Dank schonmal. Hoffentlich klappt dann auch bald die Anwendung von Filtern im LCD-Modus

**Comment by Klizzy** [comment]
@MasterLH ,

Ich habe die config parameter auch in der LCD Ansicht hinzugefügt und das readme aktualisiert. Dort ist nun zu sehen welche Konfigurationen von der LCD Ansicht nicht unterstützt werden.

Einmal das Plugin neu installieren, dann hast du auch die Änderungen ☺️

**Comment by MasterLH** [comment]
@Klizzy

Hey, vielen Dank, nun funktioniert das Plugin tatsächlich wie es sein soll.
Wenn eines Tages noch die "withoutDestination" klappt wäre es natürlich super.

Bin sehr begeistert von dem Plugin - Dankeschön nochmal!
