### ISSUE TITLE
Make type of transport configurable

### ISSUE THREAD

**Issue by pintman** [Klizzy/MMM-Vrr#2]
It would be great to have the choice to configure the type of transport - i.e. filtering out ICE/IC or other long-distance lines.

**Comment by Klizzy** [comment]
thank you for your time to submit this issue!
May i ask you what City and Station you are using in your configuration?

With that information i can see which transport types are been used on your route and include some special ones, if their are some special ones.

**Comment by pintman** [comment]
I am using "Bochum Hbf".

Thanks for your support.

**Comment by Klizzy** [comment]
sorry for long delay, but an contributor implemented it now.
You can get your intended result if you update the module. After that you only have to specify which lines should be displayed in your config. For example if you want only RE123 and RE456 you have to add the following value to your `config.js`:
`line: 'RE123,RE456'

don't hesitate to open a new issue if a problem occurs.
